title: tats-super-cool-theme
description: "tats’ super cool theme (also written as tats-super-cool-theme) is a futuristic, almost sci-fi theme that will remind you of the coolest shows of the 90s (of course im talking about my personal favorites - neon genesis evangelion and ghost in the shell)"
encoding: utf-8

exclude: ["README.md", "LICENSE", "*.gem", "*.gemspec", "Gemfile.lock"]